### ISSUE TITLE
[Camera] Create a new message type that can hold the pickled frame

### ISSUE THREAD

**Issue by thctamm** [HarvardURC/MATE_ROV#9]

**Comment by jebking** [comment]
Due to the fact that a single field of `bytes` on the protocol buffer can only hold up to 65kB,
The message type for a frame could either 
- hold many different segments of the frame using several fields of the `bytes` datatype, or
- be in the form of a part of a frame, and the sender could send several different segments of the frame in separate messages, and have the receiver reconstruct the frame after it has gotten all the data for it.
